### PR TITLE
Change image path

### PR DESCRIPTION
**Pull request by llaske**
I've regenerated [here](https://hub.docker.com/repository/docker/llaske/sugarizer-server/) the image with recent versions for Sugarizer and Sugarizer Server.
I've also add dedicated tag so I will generate future versions with different tags to ensure latest release is always there.

### CODE REVIEW

**Comment by NikhilM98** [comment]
Thanks for maintaining the new docker image!

**Comment by llaske** [comment]
@NikhilM98 Do we need to update the chart version to let helm understand that the package has been changed?

**Comment by NikhilM98** [comment]
The [SSP-Chart](https://github.com/NikhilM98/sugarizer-school-portal-chart), the chart is hosted on a Helm repository [here](https://nikhilm98.github.io/sugarizer-school-portal-chart/index.yaml). The SSP-Setup script uses this repository to [fetch and install the chart](https://github.com/NikhilM98/sugarizer-school-portal/blob/8d1571571278e6379810d623e540beab1f605fec/scripts/charts/ssp.sh#L58-L60).

However Sugarizer-Chart is not hosted anywhere, it's cloned directly from this git repository [see here](https://github.com/NikhilM98/sugarizer-school-portal-server/blob/master/Dockerfile), so there should be no caching of the helm chart.

@llaske If you want to update the Sugarizer Chart in a running SSP Deployment, you can SSH into the SSP Server container and run something like:
```
cd ../sugarizer-chart
git pull origin master
```

If it still does not works, you can try updating the chart version and try again.

**Comment by NikhilM98** [comment]
@llaske btw the SSP docker image is still maintained by me. If you want, you can update it with your docker-image [here](https://github.com/NikhilM98/sugarizer-school-portal-chart/blob/2efb20fcd4e3f18129717b2ad2b7e79d7311e012/templates/deployment.yaml#L21).

**Comment by llaske** [comment]
Ok thanks for the advice.
I can't pull the repo because it look like `values.yaml` is updated during install. So I've updated manually the `sugarizer.yaml` file and it works fine.
I'm comfortable with the fact that SSP docker image is maintained by you since the main repo is on your side.
We'll see for future updates/fixes on SSP how we could handle that.

**Pull request merged**
